fragment ArtistParts on Artist {
  __typename
  name
  tagline
  bio
  location
  activeSince
  heroImage
}

fragment ArtworksParts on Artworks {
  __typename
  title
  year
  medium
  image
  dimensions
  featured
  description
}

fragment ExhibitionsParts on Exhibitions {
  __typename
  title
  venue
  location
  startDate
  endDate
  featured
  description
}

fragment WorkshopsParts on Workshops {
  __typename
  title
  organization
  location
  date
  time
  registerUrl
  past
  description
}

fragment ComicsParts on Comics {
  __typename
  title
  year
  format
  image
  featured
  description
}
