//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  artist: Artist;
  artistConnection: ArtistConnection;
  artworks: Artworks;
  artworksConnection: ArtworksConnection;
  exhibitions: Exhibitions;
  exhibitionsConnection: ExhibitionsConnection;
  workshops: Workshops;
  workshopsConnection: WorkshopsConnection;
  comics: Comics;
  comicsConnection: ComicsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtistArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtistConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtistFilter>;
};


export type QueryArtworksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryArtworksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
};


export type QueryExhibitionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryExhibitionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExhibitionsFilter>;
};


export type QueryWorkshopsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorkshopsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkshopsFilter>;
};


export type QueryComicsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryComicsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ComicsFilter>;
};

export type DocumentFilter = {
  artist?: InputMaybe<ArtistFilter>;
  artworks?: InputMaybe<ArtworksFilter>;
  exhibitions?: InputMaybe<ExhibitionsFilter>;
  workshops?: InputMaybe<WorkshopsFilter>;
  comics?: InputMaybe<ComicsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Artist | Artworks | Exhibitions | Workshops | Comics | Folder;

export type Artist = Node & Document & {
  __typename?: 'Artist';
  name: Scalars['String']['output'];
  tagline?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  activeSince?: Maybe<Scalars['String']['output']>;
  heroImage?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArtistFilter = {
  name?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  activeSince?: InputMaybe<StringFilter>;
  heroImage?: InputMaybe<ImageFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ArtistConnectionEdges = {
  __typename?: 'ArtistConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Artist>;
};

export type ArtistConnection = Connection & {
  __typename?: 'ArtistConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArtistConnectionEdges>>>;
};

export type Artworks = Node & Document & {
  __typename?: 'Artworks';
  title: Scalars['String']['output'];
  year?: Maybe<Scalars['String']['output']>;
  medium?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  dimensions?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ArtworksFilter = {
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  medium?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  dimensions?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ArtworksConnectionEdges = {
  __typename?: 'ArtworksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Artworks>;
};

export type ArtworksConnection = Connection & {
  __typename?: 'ArtworksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ArtworksConnectionEdges>>>;
};

export type Exhibitions = Node & Document & {
  __typename?: 'Exhibitions';
  title: Scalars['String']['output'];
  venue?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  startDate?: Maybe<Scalars['String']['output']>;
  endDate?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ExhibitionsFilter = {
  title?: InputMaybe<StringFilter>;
  venue?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  startDate?: InputMaybe<StringFilter>;
  endDate?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ExhibitionsConnectionEdges = {
  __typename?: 'ExhibitionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Exhibitions>;
};

export type ExhibitionsConnection = Connection & {
  __typename?: 'ExhibitionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ExhibitionsConnectionEdges>>>;
};

export type Workshops = Node & Document & {
  __typename?: 'Workshops';
  title: Scalars['String']['output'];
  organization?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  date?: Maybe<Scalars['String']['output']>;
  time?: Maybe<Scalars['String']['output']>;
  registerUrl?: Maybe<Scalars['String']['output']>;
  past?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WorkshopsFilter = {
  title?: InputMaybe<StringFilter>;
  organization?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
  date?: InputMaybe<StringFilter>;
  time?: InputMaybe<StringFilter>;
  registerUrl?: InputMaybe<StringFilter>;
  past?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type WorkshopsConnectionEdges = {
  __typename?: 'WorkshopsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Workshops>;
};

export type WorkshopsConnection = Connection & {
  __typename?: 'WorkshopsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorkshopsConnectionEdges>>>;
};

export type Comics = Node & Document & {
  __typename?: 'Comics';
  title: Scalars['String']['output'];
  year?: Maybe<Scalars['String']['output']>;
  format?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ComicsFilter = {
  title?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  featured?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ComicsConnectionEdges = {
  __typename?: 'ComicsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Comics>;
};

export type ComicsConnection = Connection & {
  __typename?: 'ComicsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ComicsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateArtist: Artist;
  createArtist: Artist;
  updateArtworks: Artworks;
  createArtworks: Artworks;
  updateExhibitions: Exhibitions;
  createExhibitions: Exhibitions;
  updateWorkshops: Workshops;
  createWorkshops: Workshops;
  updateComics: Comics;
  createComics: Comics;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateArtistArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtistMutation;
};


export type MutationCreateArtistArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtistMutation;
};


export type MutationUpdateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationCreateArtworksArgs = {
  relativePath: Scalars['String']['input'];
  params: ArtworksMutation;
};


export type MutationUpdateExhibitionsArgs = {
  relativePath: Scalars['String']['input'];
  params: ExhibitionsMutation;
};


export type MutationCreateExhibitionsArgs = {
  relativePath: Scalars['String']['input'];
  params: ExhibitionsMutation;
};


export type MutationUpdateWorkshopsArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkshopsMutation;
};


export type MutationCreateWorkshopsArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkshopsMutation;
};


export type MutationUpdateComicsArgs = {
  relativePath: Scalars['String']['input'];
  params: ComicsMutation;
};


export type MutationCreateComicsArgs = {
  relativePath: Scalars['String']['input'];
  params: ComicsMutation;
};

export type DocumentUpdateMutation = {
  artist?: InputMaybe<ArtistMutation>;
  artworks?: InputMaybe<ArtworksMutation>;
  exhibitions?: InputMaybe<ExhibitionsMutation>;
  workshops?: InputMaybe<WorkshopsMutation>;
  comics?: InputMaybe<ComicsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  artist?: InputMaybe<ArtistMutation>;
  artworks?: InputMaybe<ArtworksMutation>;
  exhibitions?: InputMaybe<ExhibitionsMutation>;
  workshops?: InputMaybe<WorkshopsMutation>;
  comics?: InputMaybe<ComicsMutation>;
};

export type ArtistMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  activeSince?: InputMaybe<Scalars['String']['input']>;
  heroImage?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArtworksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  medium?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  dimensions?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ExhibitionsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  venue?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  startDate?: InputMaybe<Scalars['String']['input']>;
  endDate?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type WorkshopsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  organization?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  time?: InputMaybe<Scalars['String']['input']>;
  registerUrl?: InputMaybe<Scalars['String']['input']>;
  past?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ComicsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ArtistPartsFragment = { __typename: 'Artist', name: string, tagline?: string | null, bio?: string | null, location?: string | null, activeSince?: string | null, heroImage?: string | null, body?: any | null };

export type ArtworksPartsFragment = { __typename: 'Artworks', title: string, year?: string | null, medium?: string | null, image?: string | null, dimensions?: string | null, featured?: boolean | null, description?: string | null };

export type ExhibitionsPartsFragment = { __typename: 'Exhibitions', title: string, venue?: string | null, location?: string | null, startDate?: string | null, endDate?: string | null, featured?: boolean | null, description?: string | null };

export type WorkshopsPartsFragment = { __typename: 'Workshops', title: string, organization?: string | null, location?: string | null, date?: string | null, time?: string | null, registerUrl?: string | null, past?: boolean | null, description?: string | null, body?: any | null };

export type ComicsPartsFragment = { __typename: 'Comics', title: string, year?: string | null, format?: string | null, image?: string | null, featured?: boolean | null, description?: string | null, body?: any | null };

export type ArtistQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArtistQuery = { __typename?: 'Query', artist: { __typename: 'Artist', id: string, name: string, tagline?: string | null, bio?: string | null, location?: string | null, activeSince?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArtistConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtistFilter>;
}>;


export type ArtistConnectionQuery = { __typename?: 'Query', artistConnection: { __typename?: 'ArtistConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArtistConnectionEdges', cursor: string, node?: { __typename: 'Artist', id: string, name: string, tagline?: string | null, bio?: string | null, location?: string | null, activeSince?: string | null, heroImage?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ArtworksQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ArtworksQuery = { __typename?: 'Query', artworks: { __typename: 'Artworks', id: string, title: string, year?: string | null, medium?: string | null, image?: string | null, dimensions?: string | null, featured?: boolean | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ArtworksConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ArtworksFilter>;
}>;


export type ArtworksConnectionQuery = { __typename?: 'Query', artworksConnection: { __typename?: 'ArtworksConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ArtworksConnectionEdges', cursor: string, node?: { __typename: 'Artworks', id: string, title: string, year?: string | null, medium?: string | null, image?: string | null, dimensions?: string | null, featured?: boolean | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ExhibitionsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ExhibitionsQuery = { __typename?: 'Query', exhibitions: { __typename: 'Exhibitions', id: string, title: string, venue?: string | null, location?: string | null, startDate?: string | null, endDate?: string | null, featured?: boolean | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ExhibitionsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ExhibitionsFilter>;
}>;


export type ExhibitionsConnectionQuery = { __typename?: 'Query', exhibitionsConnection: { __typename?: 'ExhibitionsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ExhibitionsConnectionEdges', cursor: string, node?: { __typename: 'Exhibitions', id: string, title: string, venue?: string | null, location?: string | null, startDate?: string | null, endDate?: string | null, featured?: boolean | null, description?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type WorkshopsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WorkshopsQuery = { __typename?: 'Query', workshops: { __typename: 'Workshops', id: string, title: string, organization?: string | null, location?: string | null, date?: string | null, time?: string | null, registerUrl?: string | null, past?: boolean | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type WorkshopsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkshopsFilter>;
}>;


export type WorkshopsConnectionQuery = { __typename?: 'Query', workshopsConnection: { __typename?: 'WorkshopsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WorkshopsConnectionEdges', cursor: string, node?: { __typename: 'Workshops', id: string, title: string, organization?: string | null, location?: string | null, date?: string | null, time?: string | null, registerUrl?: string | null, past?: boolean | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ComicsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ComicsQuery = { __typename?: 'Query', comics: { __typename: 'Comics', id: string, title: string, year?: string | null, format?: string | null, image?: string | null, featured?: boolean | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ComicsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ComicsFilter>;
}>;


export type ComicsConnectionQuery = { __typename?: 'Query', comicsConnection: { __typename?: 'ComicsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ComicsConnectionEdges', cursor: string, node?: { __typename: 'Comics', id: string, title: string, year?: string | null, format?: string | null, image?: string | null, featured?: boolean | null, description?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const ArtistPartsFragmentDoc = gql`
    fragment ArtistParts on Artist {
  __typename
  name
  tagline
  bio
  location
  activeSince
  heroImage
  body
}
    `;
export const ArtworksPartsFragmentDoc = gql`
    fragment ArtworksParts on Artworks {
  __typename
  title
  year
  medium
  image
  dimensions
  featured
  description
}
    `;
export const ExhibitionsPartsFragmentDoc = gql`
    fragment ExhibitionsParts on Exhibitions {
  __typename
  title
  venue
  location
  startDate
  endDate
  featured
  description
}
    `;
export const WorkshopsPartsFragmentDoc = gql`
    fragment WorkshopsParts on Workshops {
  __typename
  title
  organization
  location
  date
  time
  registerUrl
  past
  description
  body
}
    `;
export const ComicsPartsFragmentDoc = gql`
    fragment ComicsParts on Comics {
  __typename
  title
  year
  format
  image
  featured
  description
  body
}
    `;
export const ArtistDocument = gql`
    query artist($relativePath: String!) {
  artist(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtistParts
  }
}
    ${ArtistPartsFragmentDoc}`;
export const ArtistConnectionDocument = gql`
    query artistConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArtistFilter) {
  artistConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtistParts
      }
    }
  }
}
    ${ArtistPartsFragmentDoc}`;
export const ArtworksDocument = gql`
    query artworks($relativePath: String!) {
  artworks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ArtworksParts
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const ArtworksConnectionDocument = gql`
    query artworksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ArtworksFilter) {
  artworksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ArtworksParts
      }
    }
  }
}
    ${ArtworksPartsFragmentDoc}`;
export const ExhibitionsDocument = gql`
    query exhibitions($relativePath: String!) {
  exhibitions(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ExhibitionsParts
  }
}
    ${ExhibitionsPartsFragmentDoc}`;
export const ExhibitionsConnectionDocument = gql`
    query exhibitionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ExhibitionsFilter) {
  exhibitionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ExhibitionsParts
      }
    }
  }
}
    ${ExhibitionsPartsFragmentDoc}`;
export const WorkshopsDocument = gql`
    query workshops($relativePath: String!) {
  workshops(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WorkshopsParts
  }
}
    ${WorkshopsPartsFragmentDoc}`;
export const WorkshopsConnectionDocument = gql`
    query workshopsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WorkshopsFilter) {
  workshopsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WorkshopsParts
      }
    }
  }
}
    ${WorkshopsPartsFragmentDoc}`;
export const ComicsDocument = gql`
    query comics($relativePath: String!) {
  comics(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ComicsParts
  }
}
    ${ComicsPartsFragmentDoc}`;
export const ComicsConnectionDocument = gql`
    query comicsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ComicsFilter) {
  comicsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ComicsParts
      }
    }
  }
}
    ${ComicsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      artist(variables: ArtistQueryVariables, options?: C): Promise<{data: ArtistQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtistQueryVariables, query: string}> {
        return requester<{data: ArtistQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtistQueryVariables, query: string}, ArtistQueryVariables>(ArtistDocument, variables, options);
      },
    artistConnection(variables?: ArtistConnectionQueryVariables, options?: C): Promise<{data: ArtistConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtistConnectionQueryVariables, query: string}> {
        return requester<{data: ArtistConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtistConnectionQueryVariables, query: string}, ArtistConnectionQueryVariables>(ArtistConnectionDocument, variables, options);
      },
    artworks(variables: ArtworksQueryVariables, options?: C): Promise<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}> {
        return requester<{data: ArtworksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksQueryVariables, query: string}, ArtworksQueryVariables>(ArtworksDocument, variables, options);
      },
    artworksConnection(variables?: ArtworksConnectionQueryVariables, options?: C): Promise<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}> {
        return requester<{data: ArtworksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ArtworksConnectionQueryVariables, query: string}, ArtworksConnectionQueryVariables>(ArtworksConnectionDocument, variables, options);
      },
    exhibitions(variables: ExhibitionsQueryVariables, options?: C): Promise<{data: ExhibitionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExhibitionsQueryVariables, query: string}> {
        return requester<{data: ExhibitionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExhibitionsQueryVariables, query: string}, ExhibitionsQueryVariables>(ExhibitionsDocument, variables, options);
      },
    exhibitionsConnection(variables?: ExhibitionsConnectionQueryVariables, options?: C): Promise<{data: ExhibitionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExhibitionsConnectionQueryVariables, query: string}> {
        return requester<{data: ExhibitionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ExhibitionsConnectionQueryVariables, query: string}, ExhibitionsConnectionQueryVariables>(ExhibitionsConnectionDocument, variables, options);
      },
    workshops(variables: WorkshopsQueryVariables, options?: C): Promise<{data: WorkshopsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkshopsQueryVariables, query: string}> {
        return requester<{data: WorkshopsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkshopsQueryVariables, query: string}, WorkshopsQueryVariables>(WorkshopsDocument, variables, options);
      },
    workshopsConnection(variables?: WorkshopsConnectionQueryVariables, options?: C): Promise<{data: WorkshopsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkshopsConnectionQueryVariables, query: string}> {
        return requester<{data: WorkshopsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WorkshopsConnectionQueryVariables, query: string}, WorkshopsConnectionQueryVariables>(WorkshopsConnectionDocument, variables, options);
      },
    comics(variables: ComicsQueryVariables, options?: C): Promise<{data: ComicsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComicsQueryVariables, query: string}> {
        return requester<{data: ComicsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComicsQueryVariables, query: string}, ComicsQueryVariables>(ComicsDocument, variables, options);
      },
    comicsConnection(variables?: ComicsConnectionQueryVariables, options?: C): Promise<{data: ComicsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComicsConnectionQueryVariables, query: string}> {
        return requester<{data: ComicsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ComicsConnectionQueryVariables, query: string}, ComicsConnectionQueryVariables>(ComicsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/a8320455-ba98-4570-a11d-3a3eb34db3c8/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  